language: cpp

os:
  - linux

compiler:
  - gcc

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y lua5.1 liblua5.1-dev lua5.2 liblua5.2-dev libsnappy-dev libleveldb-dev

install: make get-deps

script: make
